name: Testing LLVM on Ubuntu

on:
  push:
    branches: [ "testing", "main" ]
    paths:
      - ".github/workflows/testUbuntu.yml"
      - "build/**"
      - "lib/**"
      - "test/**"
  pull_request:
    branches: [ "testing", "main" ]
    paths:
      - ".github/workflows/testUbuntu.yml"
      - "build/**"
      - "lib/**"
      - "test/**"

env:
  LIBCLANG_PATH: /usr/lib/llvm-14/lib/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: denoland/setup-deno@v1
      with:
        deno-version: 1.30.0

    - name: Install LLVM
      run: |
        sudo apt-get install -y libclang1-14

    - name: run test
      run: deno task test