name: Testing LLVM on MacOS

on:
  push:
    branches: [ "testing", "main" ]
    paths:
      - ".github/workflows/testMacOS.yml"
      - "build/**"
      - "lib/**"
      - "test/**"
  pull_request:
    branches: [ "testing", "main" ]
    paths:
      - ".github/workflows/testMacOS.yml"
      - "build/**"
      - "lib/**"
      - "test/**"

env:
  # LIBCLANG_PATH: ${{ brew --prefix llvm@14 }}/lib/libLLVM.dylib
  # LIBCLANG_PATH: /opt/homebrew/opt/llvm@14/lib/libLLVM.dylib
  LIBCLANG_PATH: /usr/local/opt/llvm@14/lib/libLLVM.dylib

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: denoland/setup-deno@v1
      with:
        deno-version: 1.30.0
    - name: debug path
      run: brew --prefix llvm@14
    - name: list lib
      run: ls $(brew --prefix llvm@14)
    - name: list lib/lib
      run: ls $(brew --prefix llvm@14)/lib
    - name: run test
      run: deno task test