name: Testing LLVM on MacOS

on:
  push:
    branches: [ "testing", "main" ]
    paths:
      - ".github/workflows/testMacOS.yml"
      - "build/**"
      - "lib/**"
      - "test/**"
  pull_request:
    branches: [ "testing", "main" ]
    paths:
      - ".github/workflows/testMacOS.yml"
      - "build/**"
      - "lib/**"
      - "test/**"

env:
  LIBCLANG_PATH: $(brew --prefix llvm@14)/bin/clang

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: denoland/setup-deno@v1
      with:
        deno-version: 1.30.0

    - name: run test
      run: deno task test