name: Testing LLVM on Ubuntu

on:
  push:
    branches: [ "testing", "main", "deno.json" ]
    paths:
      - ".github/workflows/testUbuntu.yml"
      - "build/**"
      - "lib/**"
      - "test/**"
  pull_request:
    branches: [ "testing", "main", "deno.json" ]
    paths:
      - ".github/workflows/testUbuntu.yml"
      - "build/**"
      - "lib/**"
      - "test/**"

env:
  LIBCLANG_PATH: /usr/lib/llvm-14/lib/libclang-14.so.1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: denoland/setup-deno@v1
      with:
        deno-version: 1.30.0

    - name: Uninstall old LLVM
      run: |
        sudo apt-get remove -y libclang*

    - name: Install LLVM
      run: |
        sudo apt-get install -y libclang1-14

    - name: run test
      run: deno task test